name = "hex-determinant-mathlib"
defaultTargets = ["HexDeterminantMathlib"]

[[require]]
name = "HexDeterminant"
git = "https://github.com/kim-em/hex-determinant.git"
rev = "38f9ee5f8ccf11923e9d94723863e1490ea776a2"

[[require]]
name = "HexBareiss"
git = "https://github.com/kim-em/hex-bareiss.git"
rev = "a433e76ef973bb7f8d1d20d110b1d8014d3d4f9b"

[[require]]
name = "HexMatrixMathlib"
git = "https://github.com/kim-em/hex-matrix-mathlib.git"
rev = "402c2a9b7ddc7b2d0b87f2fad26a1b5ecd639bd0"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.30.0-rc2"

[[lean_lib]]
name = "HexDeterminantMathlib"
