name = "hex-determinant-mathlib"
defaultTargets = ["HexDeterminantMathlib"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexBasic"
git = "https://github.com/leanprover/hex-basic.git"
rev = "a47240943e925951a676d1a1c2f2a615ae68fdef"

[[require]]
name = "HexDeterminant"
git = "https://github.com/leanprover/hex-determinant.git"
rev = "2c122657aee7dcd9f7a619dc0d8971a3415e127a"

[[require]]
name = "HexBareiss"
git = "https://github.com/leanprover/hex-bareiss.git"
rev = "23ac1d50878f839e306c2f395a9ac576b352f06b"

[[require]]
name = "HexMatrixMathlib"
git = "https://github.com/leanprover/hex-matrix-mathlib.git"
rev = "7e610d89729859968ae51cbbecb8aaef537d7225"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.34.0-rc2"

[[lean_lib]]
name = "HexDeterminantMathlib"
