name = "hex-determinant-mathlib"
defaultTargets = ["HexDeterminantMathlib"]

[[require]]
name = "HexDeterminant"
git = "https://github.com/kim-em/hex-determinant.git"
rev = "2b8a673897668d6368819a83f24418cbd3fedb2b"

[[require]]
name = "HexBareiss"
git = "https://github.com/kim-em/hex-bareiss.git"
rev = "7cf09502518293004d9db07362103a3f17c07123"

[[require]]
name = "HexMatrixMathlib"
git = "https://github.com/kim-em/hex-matrix-mathlib.git"
rev = "93a12c73229d235efd1a7f514c2b1db985fcb458"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.30.0-rc2"

[[lean_lib]]
name = "HexDeterminantMathlib"
